#Site Settings
title: "Chinmay Savadikar"
baseurl: ""
url: "https://savadikarc.github.io"
rants: false
thumbnail-url: "/assets/thumbnails/"

# Social Media
social:
    _github: 
        base: "https://github.com/"
        username: savadikarc
    _twitter: 
        base: "https://twitter.com/"
        username: savadikarc
    _linkedin: 
        base: "https://www.linkedin.com/in/"
        username: savadikar-chinmay

#Build Settings
markdown: kramdown
permalink: pretty

plugins:
    - jekyll-redirect-from